### ISSUE TITLE
Suggestion: Add a clang-format file to enforce a coding standard.

### ISSUE THREAD

**Issue by OmniBlade** [jeff-1amstudios/dethrace#4]
Adding a clang-format file will make it easier to ensure code is formatted according to a particular format and will improve the consistency of the project as it is developed.

**Comment by jeff-1amstudios** [comment]
Yes, love the idea.

Do you have a particular one in mind?  I found https://webkit.org/code-style-guidelines/ to be easy to get a good feel for the style, and I didn't see anything that I didn't strongly disagree with.
